Multiple matches
canadianveggie/wordle-junior pull request #3
Opened 2022-01-22 07:32 UTC by canadianveggie

New logic for comparing target and guess

Diverges from Wordle logic.
Shows matches of duplicate characters.
I kind of like how it simplifies the matching logic.
Question: do we also show it on the keyboard?
<img width="451" alt="Screen Shot 2022-01-21 at 11 18 14 PM" src="https://user-images.githubusercontent.com/513961/150629408-258ada97-4564-4381-895b-50893f029b16.png">

2022-01-22 21:13 UTC, wachunga requested changes

2022-01-22 21:13 UTC, wachunga commented on public/emojis.js
> +  RATS: "🐀🐀",
💯

2022-01-22 21:13 UTC, wachunga commented on public/puzzles.js
> +    const otherMatches = target
problem: target FEET

![image](https://user-images.githubusercontent.com/438545/150654355-1de18b76-8e56-4aa1-820c-a0e25f5a617a.png)

2022-01-22 21:14 UTC, wachunga commented on public/puzzles.js
> +    const otherMatches = target
To clarify: it suggests there are 4 letter Es to me. If we go with this approach, I think it should only show once

2022-01-24 03:18 UTC, canadianveggie commented
Not doing this.

2022-01-24 03:18 UTC, closed without merging